// 캐릭터 코드, 이름, 이미지 경로를 매핑하는 데이터 파일입니다.
// 이미지 경로는 public 폴더를 기준으로 합니다. 커위커
export const characterInfo = {
  1: { name: '재키', image: '/images/characters/default_mini_Jackie.png' },
  2: { name: '아야', image: '/images/characters/default_mini_Aya.png' },
  3: { name: '피오라', image: '/images/characters/default_mini_Fiora.png' },
  4: { name: '매그너스', image: '/images/characters/default_mini_Magnus.png' },
  5: { name: '자히르', image: '/images/characters/default_mini_Zahir.png' },
  6: { name: '나딘', image: '/images/characters/default_mini_Nadine.png' },
  7: { name: '현우', image: '/images/characters/default_mini_Hyunwoo.png' },
  8: { name: '하트', image: '/images/characters/default_mini_Hart.png' },
  9: { name: '아이솔', image: '/images/characters/default_mini_Isol.png' },
  10: { name: '리 다이린', image: '/images/characters/default_mini_LiDailin.png' },
  11: { name: '유키', image: '/images/characters/default_mini_Yuki.png' },
  12: { name: '혜진', image: '/images/characters/default_mini_Hyejin.png' },
  13: { name: '쇼우', image: '/images/characters/default_mini_Xiukai.png' },
  14: { name: '키아라', image: '/images/characters/default_mini_Chiara.png' },
  15: { name: '시셀라', image: '/images/characters/default_mini_Sissela.png' },
  16: { name: '실비아', image: '/images/characters/default_mini_Silvia.png' },
  17: { name: '아드리아나', image: '/images/characters/default_mini_Adriana.png' },
  18: { name: '쇼이치', image: '/images/characters/default_mini_Shoichi.png' },
  19: { name: '엠마', image: '/images/characters/default_mini_Emma.png' },
  20: { name: '레녹스', image: '/images/characters/default_mini_Lenox.png' },
  21: { name: '로지', image: '/images/characters/default_mini_Rozzi.png' },
  22: { name: '루크', image: '/images/characters/default_mini_Luke.png' },
  23: { name: '캐시', image: '/images/characters/default_mini_Cathy.png' },
  24: { name: '아델라', image: '/images/characters/default_mini_Adela.png' },
  25: { name: '버니스', image: '/images/characters/default_mini_bERnice.png' },
  26: { name: '바바라', image: '/images/characters/default_mini_Barbara.png' },
  27: { name: '알렉스', image: '/images/characters/default_mini_Alex.png' },
  28: { name: '수아', image: '/images/characters/default_mini_Sua.png' },
  29: { name: '레온', image: '/images/characters/default_mini_Leon.png' },
  30: { name: '일레븐', image: '/images/characters/default_mini_Eleven.png' },
  31: { name: '리오', image: '/images/characters/default_mini_Rio.png' },
  32: { name: '윌리엄', image: '/images/characters/default_mini_William.png' },
  33: { name: '니키', image: '/images/characters/default_mini_Nicky.png' },
  34: { name: '나타폰', image: '/images/characters/default_mini_Nathapon.png' },
  35: { name: '얀', image: '/images/characters/default_mini_Jan.png' },
  36: { name: '이바', image: '/images/characters/default_mini_Eva.png' },
  37: { name: '다니엘', image: '/images/characters/default_mini_Daniel.png' },
  38: { name: '제니', image: '/images/characters/default_mini_Jenny.png' },
  39: { name: '카밀로', image: '/images/characters/default_mini_Camilo.png' },
  40: { name: '클로에', image: '/images/characters/default_mini_Chloe.png' },
  41: { name: '요한', image: '/images/characters/default_mini_Johann.png' },
  42: { name: '비앙카', image: '/images/characters/default_mini_Bianca.png' },
  43: { name: '셀린', image: '/images/characters/default_mini_Celine.png' },
  44: { name: '에키온', image: '/images/characters/default_mini_Echion.png' },
  45: { name: '마이', image: '/images/characters/default_mini_Mai.png' },
  46: { name: '에이든', image: '/images/characters/default_mini_Aiden.png' },
  47: { name: '라우라', image: '/images/characters/default_mini_Laura.png' },
  48: { name: '띠아', image: '/images/characters/default_mini_Tia.png' },
  49: { name: '펠릭스', image: '/images/characters/default_mini_Felix.png' },
  50: { name: '엘레나', image: '/images/characters/default_mini_Elena.png' },
  51: { name: '프리야', image: '/images/characters/default_mini_Priya.png' },
  52: { name: '아디나', image: '/images/characters/default_mini_Adina.png' },
  53: { name: '마커스', image: '/images/characters/default_mini_Markus.png' },
  54: { name: '칼라', image: '/images/characters/default_mini_Karla.png' },
  55: { name: '에스텔', image: '/images/characters/default_mini_Estelle.png' },
  56: { name: '피올로', image: '/images/characters/default_mini_Piolo.png' },
  57: { name: '마르티나', image: '/images/characters/default_mini_Martina.png' },
  58: { name: '헤이즈', image: '/images/characters/default_mini_Haze.png' },
  59: { name: '아이작', image: '/images/characters/default_mini_Isaac.png' },
  60: { name: '타지아', image: '/images/characters/default_mini_Tazia.png' },
  61: { name: '이렘', image: '/images/characters/default_mini_Irem.png' },
  62: { name: '테오도르', image: '/images/characters/default_mini_Theodore.png' },
  63: { name: '이안', image: '/images/characters/default_mini_Lyanh.png' },
  64: { name: '바냐', image: '/images/characters/default_mini_Vanya.png' },
  65: { name: '데비&마를렌', image: '/images/characters/default_mini_DebiMarlene.png' },
  66: { name: '아르다', image: '/images/characters/default_mini_Arda.png' },
  67: { name: '아비게일', image: '/images/characters/default_mini_Abigail.png' },
  68: { name: '알론소', image: '/images/characters/default_mini_Alonso.png' },
  69: { name: '레니', image: '/images/characters/default_mini_Leni.png' },
  70: { name: '츠바메', image: '/images/characters/default_mini_Tsubame.png' },
  71: { name: '케네스', image: '/images/characters/default_mini_Kenneth.png' },
  72: { name: '카티야', image: '/images/characters/default_mini_Katja.png' },
  73: { name: '샬럿', image: '/images/characters/default_mini_Charlotte.png' },
  74: { name: '다르코', image: '/images/characters/default_mini_Darko.png' },
  75: { name: '르노어', image: '/images/characters/default_mini_Lenore.png' },
  76: { name: '가넷', image: '/images/characters/default_mini_Garnet.png' },
  77: { name: '유민', image: '/images/characters/default_mini_Yumin.png' },
  78: { name: '히스이', image: '/images/characters/default_mini_Hisui.png' },
  79: { name: '유스티나', image: '/images/characters/default_mini_Justyna.png' },
  80: { name: '이슈트반', image: '/images/characters/default_mini_Istvan.png' },
  81: { name: '니아', image: '/images/characters/default_mini_NiaH.png' },
  82: { name: '슈린', image: '/images/characters/default_mini_Xuelin.png' },
  83: { name: '헨리', image: '/images/characters/default_mini_Henry.png' },
  84: { name: '블레어', image: '/images/characters/default_mini_Blair.png' },
  85: { name: '미르카', image: '/images/characters/default_mini_Mirka.png' },
  86: { name: '펜리르', image: '/images/characters/default_mini_Fenrir.png' },
  87: { name: '코렐라인', image: '/images/characters/default_mini_Coraline.png' },
  default: { name: '알 수 없음', image: '/char_placeholder.png' }
};

// 캐릭터 코드를 받으면 해당 캐릭터의 정보를 반환하는 헬퍼 함수
export const getCharacterInfo = (code) => {
  return characterInfo[code] || characterInfo.default;
};
